name: Build Windows x64

on:
  push:
    tags: [ '**' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: latest

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Configure Git to use HTTPS
      run: git config --global url."https://github.com/".insteadOf git://github.com/

    - name: Generate resources
      shell: bash
      run: |
        cd translate
        pip install -r requirements.txt
        ./gen_rc.sh

    - name: Restore NuGet packages
      run: nuget restore AudioPlaybackConnector.sln

    - name: Build x64 Release
      shell: powershell
      run: |
        msbuild AudioPlaybackConnector.sln `
          -p:Configuration=Release `
          -p:Platform=x64

    - name: Upload x64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: AudioPlaybackConnector-x64
        path: x64/Release/AudioPlaybackConnector64.exe